### ISSUE TITLE
Fix please

### ISSUE THREAD

**Issue by GoodGooGleINS** [pusher/docs#106]
chrome-distiller://693fff3d-db6c-4c44-81bb-bddd51104b6e_b3bd077a0dbb027b060c45375791a02d83b1eeb3b71bceaadeb24aea9348933d/?title=https%3A%2F%2Fgameserver02.lucky897.com%2Frgs%2Fviews%2Flucky%2Fembed.html%3Fsid%3DS9fe649575d68%26home%3Dhttps%3A%2F%2Fm.bspin.io%2Fcategory%2Fbitcoin-all-games%2F%3FgoBack%3Dgame-5779&url=https%3A%2F%2Fgameserver02.lucky897.com%2Frgs%2Fviews%2Flucky%2Fembed.html%3Fsid%3DS9fe649575d68%26home%3Dhttps%3A%2F%2Fm.bspin.io%2Fcategory%2Fbitcoin-all-games%2F%3FgoBack%3Dgame-5779

**Comment by benw-pusher** [comment]
There isn't enough info here to proceed so I'll close this, if you want to reopen please provide a full description of the issue.
