### ISSUE TITLE
Pusher Channels Docs | How to build presence channelspage: max number of users wrong?

### ISSUE THREAD

**Issue by anlauren** [pusher/docs#129]
Hello there, I spotted an issue on https://pusher.com/docs/channels/using_channels/presence-channels/

We have just tested to go to more than a hundred in a presence channel, to see if it would crash our implementation or not, and turns out we can go above that limit?

What's the actual limit? What would happen when the N+1 user connects to that presence channel? would it raise an exception or just generate an `pusher:subscription_error`event on the channel?

Thanks

**Comment by benw-pusher** [comment]
When you attempt to subscribe to a presence channel that has reached its limit you will receive an error such as: 
`{"event":"pusher:error","data":{"code":null,"message":"For channel presence-channel-name: too many users"}}]`

You can bind to these errors using:

**Comment by anlauren** [comment]
Alright thanks! 
It was a bit hard for us to test what would happen in case there are too many people on the channel since we didn't know where was the hard limit ;p

**Comment by benw-pusher** [comment]
Makes sense, hopefully the info shared is enough to allow you to proceed. I'll close this but feel free to reopen if not.
