### ISSUE TITLE
Pusher Channels Error

### ISSUE THREAD

**Issue by Choo99** [pusher/docs#130]
Hello there, I spotted an issue on https://
![image](https://user-images.githubusercontent.com/80664190/143893740-546059fb-5419-4e4a-b78a-bbf6cb0ab386.png)
pusher.com/docs/channels/using_channels/connection/

I'm using Pusher for my ionic project. The server can connects with my app at first but after certain times or after making many requests and this error will come out and disconnect the running of the server. How can I fix this?

**Comment by benw-pusher** [comment]
This could be a capacity issue on your publishing server - you mention that this happens after making many requests. Do you know if the threadpool is configured to facilitate a large number of requests in a short time? The threadpool can be configured through the 'UV_THREADPOOL_SIZE' node setting.

**Comment by benw-pusher** [comment]
I'll close this out as I haven't heard from you following my recent update.
