### ISSUE TITLE
README.md refers to absent documtation

### ISSUE THREAD

**Issue by ArnoSoontjens** [pusher/docs#133]
When reading the README of pusher-http-node it says "The channel_name in the path must be a presence channel. The structure of the returned JSON is defined in the [REST API reference](https://pusher.com/docs/channels/library_auth_reference/rest_api/#method-get-users)" which refers to "https://pusher.com/docs/channels/library_auth_reference/rest_api/#method-get-users", but that page does not exist.
Where can I find the structure of the json?

**Comment by amad** [comment]
This issue didn't reach our backlog somehow. Sorry for the delay.

Correct link is https://pusher.com/docs/channels/library_auth_reference/rest-api/#get-users
