### ISSUE TITLE
Pusher Channels Docs | Sending events to authenticated userspage

### ISSUE THREAD

**Issue by oelerpearler** [pusher/docs#175]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/server-to-user-messages/

![image](https://user-images.githubusercontent.com/982123/171448104-65743813-e9cc-453e-b2d1-916dc346dd25.png)

The method `sendToUser` does not seem to exist neither on the server side library (https://www.npmjs.com/package/pusher) nor on the client library (https://www.npmjs.com/package/pusher-js), which is actually a shame, would have been helpful for me to invoke a specific event to one particular user (and excluding all other participants via socketId seems rather counter-intuitive and cumbersome to implement. Either way, guess the docs need to be updated here? Please let me know in case I'm wrong with my observation.

Thanks

PS: Pusher rocks, this is the very first issue I've encountered so far (after weeks of working with it), so imo you have a really good service offered here (including documentation etc.)

**Comment by oelerpearler** [comment]
Hi @benw-pusher ! Thanks for the super quick response! Oh, my bad, I haven't thought about the possibility that this method is only from 5.1.0-beta on available (in our service we use 5.0.1). I know it doesn't happen too often, but maybe it would be helpful also for others to have in the docs certain hints (e.g. a label/tag) available if a feature has been introduced during a minor version? Either way; Even though it is called 5.1.0-beta, is the version considered stable for production use? I guess so, but it was a reason why we didn't upgrade it right away.

**Comment by benw-pusher** [comment]
Yep, the feature is ready for production use. We use the `beta` label as the feature isn't rolled out to every library at this stage, but there should be no concern with rolling our this version to production.

**Comment by oelerpearler** [comment]
Thank you for the clarification. We're indeed currently implementing this method in one of our use cases, thus really glad to hear that.
