### ISSUE TITLE
Pusher Channels | API Librariespage

### ISSUE THREAD

**Issue by miguel-fulfil** [pusher/docs#177]
Hello there, I spotted an issue on https://pusher.com/docs/channels/channels_libraries/libraries/
AngularJS (uses JavaScript library) is listed as a client, which is accurate. However, it's really AngularJS (version 1.x) so it's not recommended for a LTS version of Angular.

**Comment by benjamin-tang-pusher** [comment]
Hi Miguel, our documentation is not incorrect, as the Github Readme states that library only supports version 1. We have no plans to update the library for version 2, although you may be able to use our main pusher-js library.
