### ISSUE TITLE
Pusher Channels Docs | How to authenticate userspage

### ISSUE THREAD

**Issue by oelerpearler** [pusher/docs#179]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/authenticating-users/

If I'm not mistaken, there seem to be two little inconsistencies between the node-js lib and the documentation:
- The code example in https://pusher.com/docs/channels/server_api/authenticating-users/#user-authentication suggests to provide a user object that hast an id with an integer `const user = {id: 12345};` However, the code itself would throw an error if a numerical id would be used, since it expects it to be a string: https://github.com/pusher/pusher-http-node/blob/64a7bd3f0fad5bd91edce4337902120de66a347f/lib/pusher.js#L38
- Furthermore in https://pusher.com/docs/channels/server_api/authenticating-users/#response it suggest that the return value of the newly introduced `authenticateUser` method (which needs to be sent back to the client) has a `auth` and a `user_info` property. But currently I'm having issues with implementing this new method and after inspecting the return value, I see that there is no `user_info` property, but a `user_data` property `{  auth: '0bf3ca55460a71bc0379:a5f32c4391092874059b6787bc91c777d827b85877981f59b2d56a44e89ed897', user_data: '{"id":"abc"}' }`. Of course the pusher node library provides this value and any implementation has only to forward this response to the client, but still I guess it would be better to ensure to correct this in docs as well.

Let me know in case I misunderstood something (and the docs are actually completely fine).

**Comment by benjamin-tang-pusher** [comment]
You're right on both counts, without a string it will throw an error, and that should be user_data, not user_info. I will get that changed.

**Comment by benjamin-tang-pusher** [comment]
I've corrected the type and name so I will close this issue. Thanks for bringing it up.
