### ISSUE TITLE
Pusher Channels Docs | How to authenticate userspage

### ISSUE THREAD

**Issue by prakashtest** [pusher/docs#181]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/authenticating-users/

The code snippet shown is 
`const authResponse = pusher.authenticateUser(socketId, user);`

However the code example shows the usage as 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/17311677/176231781-d30e881a-3909-46ec-a736-481257cd9297.png">

Which one is to be used , I could not find `authenticateUser` function in pusher there is just `authenticate`

**Comment by benw-pusher** [comment]
Hi, you should use AuthenticateUser for the Users feature described at https://pusher.com/docs/channels/server_api/authenticating-users/. Could you share where you found the code in the screenshot so I can correct?

**Comment by benw-pusher** [comment]
HI, to be able to resolve we need a little more info. I'll close this out but if you are able to share more info please do so.
