### ISSUE TITLE
Pusher Channels Docs | HTTP API Referencepage

### ISSUE THREAD

**Issue by ABCINC2017** [pusher/docs#195]
Hello there, I spotted an issue on https://pusher.com/docs/channels/library_auth_reference/rest-api/ [New Recording - 7/19/2022, 11:06:36 AM](https://vimeo.com/731404669/525bfb0de9)

**Comment by benw-pusher** [comment]
Hi, You can change the URL that opens when the user clicks the notification with the deep_link payload. See https://pusher.com/docs/beams/reference/publish-payloads/#deep_link-132083545. 

This issue board is for errors in the documentation and not implementation/configuration issues - I will close this github however if you need more info or support please get in touch with us via https://support.pusher.com/hc/en-us/requests/new
