### ISSUE TITLE
Pusher Channels Docs | CLI Functionalitypage

### ISSUE THREAD

**Issue by miguel-fulfil** [pusher/docs#197]
Hello there, I spotted an issue on https://pusher.com/docs/channels/pusher_cli/documentation/
I suspect that the cli doesn't take cluster into account.
/apps.json returns nothing. but when using https://api-us3.pusher.com and the nightmare to create a postman request with that, in fact I do have apps.

**Comment by benw-pusher** [comment]
Closing this in favour of https://github.com/pusher/cli/issues/50
