### ISSUE TITLE
Sending events to authenticated users

### ISSUE THREAD

**Issue by trunghieu7088** [pusher/docs#200]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/server-to-user-messages/

the method sendToUser does not exist

**Comment by benjamin-tang-pusher** [comment]
Hi, the sendToUser method is referring to is a method in our Node server library:https://github.com/pusher/pusher-http-node/blob/51bbd628b7155bc5d58b9149babe33a61869ff33/lib/pusher.js#L168 , not the client pusher-js library. Were you looking at the pusher-js library? If so, I may need to clarify that as node, and not javascript.

**Comment by benjamin-tang-pusher** [comment]
Please clarify which library you're trying to call sendToUser, I will close this ticket in the meantime.
