### ISSUE TITLE
Pusher Channels Docs | How to authenticate userspage - Code Typo

### ISSUE THREAD

**Issue by SaintPeter** [pusher/docs#214]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/authenticating-users/

In the **Client-side: setting the authentication endpoint** section, there is an extra closing parenthesis.
```js
new Pusher("app_key", { userAuthentication: { endpoint: "/pusher_user_auth.php"}));  // <-- Extra closing parenthesis
```

**Comment by benjamin-tang-pusher** [comment]
Thanks for that. Actually the second to last closing bracket should be curly.

I will get this fixed.
