### ISSUE TITLE
Page not found in docs

### ISSUE THREAD

**Issue by humphrayLegare** [pusher/docs#229]
https://pusher.com/docs/channels/server_api/watchlist-events/
 page not found

**Comment by benw-pusher** [comment]
Can you share where you found that link so we can correct?

**Comment by humphrayLegare** [comment]
on the page https://pusher.com/docs/channels/using_channels/events/#user-id-in-client-events

in section "∞ <https://pusher.com/docs/channels/using_channels/events/#binding-on-the-users-watchlist> Binding on the user’s Watchlist" 

the paragraph goes as  : 

"You can bind to events on the pusher.user.watchlist object. That means you will receive events about the Watchlist of the user authenticated on that connection. Refer to User authentication <https://pusher.com/docs/channels/using_channels/user-authentication> for more information on authenticating users. Refer to Watchlist events <https://pusher.com/docs/channels/server_api/watchlist-events> for more information on how to provide the user’s Watchlist and how to enable Watchlist events."

Dead link is when clicking Refer to Watchlist events.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Nov 21, 2022, 05:28 by ***@***.***:

**Comment by benw-pusher** [comment]
Thanks, I will rectify this!
