### ISSUE TITLE
Pusher Beams Docs | Web SDKpage

### ISSUE THREAD

**Issue by ashfahan** [pusher/docs#239]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/web/

The title of the tab should have been Npm / Yarn.
![image](https://user-images.githubusercontent.com/19289015/210085448-075c6520-cb19-466c-9a34-7a882c3fdd09.png)

**Comment by benw-pusher** [comment]
[npm](https://www.npmjs.com/) appears to be referenced in lowercase across their documentation, however I will update Yarn to use a capital `Y` character as per their docs.
