### ISSUE TITLE
Pusher Channels Docs | Server API Overviewpage

### ISSUE THREAD

**Issue by olivereisenhut** [pusher/docs#265]
Hello there, I spotted an issue on https://pusher.com/docs/channels/server_api/overview/

There is this note: 

> Note! If you created your app in a different cluster to the default us-east-1, you must configure the cluster option as well. [See how](https://pusher.com/docs/channels/miscellaneous/clusters).

Though, the link from the note gives a list of clusters which does not include 'us-east-1' but the following:

> [∞](https://pusher.com/docs/channels/miscellaneous/clusters/#what-clusters-exist?) What clusters exist?
> Channels has the following public clusters:
> 
> mt1 in N. Virginia
> us2 in Ohio
> us3 in Oregon
> eu in Ireland
> ap1 in Singapore
> ap2 in Mumbai
> ap3 in Tokyo
> ap4 in Sydney
> sa1 in São Paulo

What is the correct default cluster?

**Comment by benw-pusher** [comment]
Woah, you are quite correct. Don't know how we missed this. In fact, the cluster should always be specified. I will update with the necessary instructions.
