### ISSUE TITLE
4005 page not found

### ISSUE THREAD

**Issue by omaranwaar** [pusher/docs#269]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/130358317/234994958-c51e4431-1737-4a19-9a02-3e5b78026bf6.png">

Hello there, My channel is public for that I don't need to add any authentication endpoint. I am just following the Docs but I am unable to make a connection. 

A speedy help would be appreciated.

**Comment by benw-pusher** [comment]
This space is open for raising errors found in the docs, for implementation issues it is best to contact us directly - could you get in touch with us at https://support.pusher.com/hc/en-us/requests/new so we can help further? Please share your app key/id when raising the ticket so we can investigate fully.
