### ISSUE TITLE
Pusher Beams Docs | What are subscribers in Beams?page

### ISSUE THREAD

**Issue by juanlizarazo** [pusher/docs#285]
Hello Support Team! I am a premium customer. I have a question on https://pusher.com/docs/beams/concepts/subscribers/

> (...) The old Subscribers will be removed by our automated device cleanup procedure.

Regarding the automated cleanup in your Beams documentation, how often does it run? Specifically, after how many days of inactivity will a device be cleared?

**Comment by benjamin-tang-pusher** [comment]
Hi, after uninstalling an Android app, it should be removed from Beams in about one day. For iOS it may take several days to ensure user privacy.

We do not remove a device if its inactive. The user either must uninstall the app, or your app must call the .stop() method.

**Comment by benjamin-tang-pusher** [comment]
I will close this ticket due to no further responses.
