### ISSUE TITLE
Pusher Beams Docs | PHP Server SDKpage - Generate Token

### ISSUE THREAD

**Issue by aj-norman** [pusher/docs#291]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/server-sdk-php/ while generating a token. The `generateToken` method call returns a `string[]` not a `string` literal.

https://github.com/pusher/push-notifications-php/blob/master/src/PushNotifications.php#L187 - lines 202-204 for reference

**Comment by aj-norman** [comment]
Also noticed the GenerateToken example has the incorrect syntax, should be `->` instead of `.`

**Comment by benjamin-tang-pusher** [comment]
Corrected, thanks for raising.
