### ISSUE TITLE
Pusher Beams Docs | Kotlin & Java Client SDKs for Androidpage

### ISSUE THREAD

**Issue by bqfa** [pusher/docs#293]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/android/

I didn't get custom push notification payload when app is closed.
When app is not in foreground **onMessageReceived** not called.

` override fun onMessageReceived(remoteMessage: RemoteMessage)
{
Log.i("NotificationsService", "Got a remote message 🎉")
// TODO: Do something useful here
}`

**Comment by benw-pusher** [comment]
You may need to review https://pusher.com/docs/beams/guides/handle-incoming-notifications/android/#handle-all-notifications - this mentions: 
> When your application is in the background this service will not be called unless there is only a data payload in the notification. The notification key cannot be used.

If you follow the instructions in that guide you should be able to implement what you are looking for.
