### ISSUE TITLE
Pusher Channels Docs | React Native M1

### ISSUE THREAD

**Issue by omaranwaar** [pusher/docs#305]
Hello there, I spotted an issue on https://pusher.com/docs/channels/getting_started/react-native/ 
There is no documentation for M1 architecture install and compatibility.

**Comment by benjamin-tang-pusher** [comment]
Hi, M1 is supported, and the install instructions are the same, so it isn't necessary to explicitly mention this architecture. Any M1 specific questions will apply to React Native as a whole, not just our library.
