### ISSUE TITLE
Pusher Beams Docs | What are subscribers in Beams?page

### ISSUE THREAD

**Issue by abons** [pusher/docs#315]
Hello there, I spotted an issue on https://pusher.com/docs/beams/concepts/subscribers/

Subscribers count doesn't seem to go down, how can I force remove old subscribers?
We had 6600 unique user logins on android/ios
But the subscriber count reached the 10000 limit, why is that?

**Comment by benw-pusher** [comment]
You can see how to remove old subscribers on the page you visited - https://pusher.com/docs/beams/concepts/subscribers/#how-do-i-avoid-being-charged-for-devices-im-not-publishing-to?. 

Beams doesn't recognise unique users, it is based on devices. It could be that you are registering multiple devices per user and this is why you are experiencing increased subscriber counts. It would be best if you [reach out to us at support](https://messagebird.com/support-center/Pusher-request-new) and we can assist there.
