### ISSUE TITLE
Pusher Channels Docs | Flutter Quick Start Guidepage

### ISSUE THREAD

**Issue by slackvishal** [pusher/docs#316]
Hello there, I spotted an issue on https://pusher.com/docs/channels/getting_started/flutter/
When I am trying to subscribe to channels, the connection state becomes disconnected and it says "path not found". This happens in both public and private channels. What am i missing? I am not sure where I was wrong? Could someone help me with this issue?

**Comment by benw-pusher** [comment]
Can you get in touch with us at https://messagebird.com/support-center/Pusher-request-new and share the full error message along with the code in use so we can investigate? You have raised this issue against our docs but this doesn't look to be an error in the docs.
