### ISSUE TITLE
Pusher Beams Docs | Web SDK Integrationpage

### ISSUE THREAD

**Issue by ThilinaV98** [pusher/docs#318]
Hello there, I spotted an issue on https://pusher.com/docs/beams/getting-started/web/sdk-integration/

Getting 2 errors mention in below.
1. The script has an unsupported MIME type ('text/html').
2. Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/service-worker.js?pusherBeamsWebSDKVersion=1.1.0'): The script has an unsupported MIME type ('text/html').

Try to fix it but didn't found a solution for it.

**Comment by benw-pusher** [comment]
Can you share how you are registering the service worker (including the code)?
