### ISSUE TITLE
 Could not resolve com.google.code.gson:gson:2.7-SNAPSHOT.

### ISSUE THREAD

**Issue by anuj2285** [pusher/docs#319]
Hello there, I am getting an error while making the build.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.code.gson:gson:2.+.
     Required by:
         project :app > project :pusher_pusher-websocket-react-native
      > Could not resolve com.google.code.gson:gson:2.7-SNAPSHOT.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/google/code/gson/gson/2.7-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/google/code/gson/gson/2.7-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by benw-pusher** [comment]
This looks like it could be related to an outage at Maven. https://status.maven.org/incidents/d7hy7j6q3jhb
Are you able to build now?
