### ISSUE TITLE
Pusher Beams | Face issues with Safari 

### ISSUE THREAD

**Issue by deeshinde** [pusher/docs#321]
Pusher Beams web push works fine with Chrome. 
Have followed the setup for Safari, but do not get the prompt to enable permissions in Safari. No notifications received on Safari.

In client code , i have tried with versions **2.0.1 , 2.0.0-beta.** 

I get below error in the console . I have called `.start` on component load inside Effect hook  :

```
"Unhandled Promise rejection:"Could not add Device Interest. SDK not registered with Beams. Did you call .start?""; Zone:""<root>""; Task:""Promise.then""; Value:" 
Error: Could not add Device Interest. SDK not registered with Beams. Did you call .start? "
```

**Comment by benw-pusher** [comment]
Could you share the code in use?

**Comment by deeshinde** [comment]
Was able to resolve this
