### ISSUE TITLE
Pusher Beams Docs | Publish notifications to Android devicespage

### ISSUE THREAD

**Issue by arijit0024** [pusher/docs#327]
Hello there, I spotted an issue on https://pusher.com/docs/beams/getting-started/android/publish-notifications/

how to i add image 

web: {
      notification: {
        title: "Hello thi is ",
        body: "Hello, world! 2 baby",
        deep_link: "https://www.pusher.com",
      }, 

in this data

**Comment by benw-pusher** [comment]
HI, 
You can control the full payload of android messages as per https://pusher.com/docs/beams/reference/publish-payloads/#fcm-format. The link there also shows how to specify icons. 

The icon can also be specified for web push as per https://pusher.com/docs/beams/reference/publish-payloads/#icon-506644079. 

Thanks
Ben
