### ISSUE TITLE
Pusher Channels Docs | How to build private channelspage

### ISSUE THREAD

**Issue by MohamedSayedBayoumy** [pusher/docs#329]
Hello there, I spotted an issue on https://pusher.com/docs/channels/using_channels/private-channels/

Now i flutter app , how i can subscribe on private channel , docs don't give me as Mobile Developer all information or requirement to that , now me and backend developer doesn't have any idea about issue and onAuthorizer fun return me 403 status code , what issue what should i do , now it's working with JavaScript fun , But with Flutter App What issue  !! ..

**Comment by benw-pusher** [comment]
Could you share the error message you are receiving along with the code that is throwing the error?

**Comment by MohamedSayedBayoumy** [comment]
I find solve , issue come from back end developer , after search find it solution back end should be add this to work with mobile stable , with out this code onAuthorizer back to me 403 .. 

https://stackoverflow.com/questions/78165029/api-broadcasting-auth-403-forbidden ..
