### ISSUE TITLE
Pusher Channels Docs | What is a connection?page

### ISSUE THREAD

**Issue by hagen** [pusher/docs#339]
Hello there, I spotted an issue on https://pusher.com/docs/channels/using_channels/connection/

Under the heading [`channelAuthorization`](https://pusher.com/docs/channels/using_channels/connection/#channelauthorization-1528180693), the description reads:

> Object containing the configuration for _user_ authorization.

<img width="845" alt="image" src="https://github.com/user-attachments/assets/ed989f77-7a3f-4f3f-93de-2e7e1c13503f">

I believe this should be _channel_ authorization?

**Comment by evgeniibreikin** [comment]
Thanks, @hagen
