### ISSUE TITLE
Broken link to a webhook doc

### ISSUE THREAD

**Issue by tomdos** [pusher/docs#35]
When I go to webhooks page under `Home -> Channels -> my app`, there is link in:
```
Webhooks

Webhooks allow your server to be notified about events occurring within your Channels app. Learn more in our Webhook documentation.
```

The link to `Webhook documentation` is broken.

**Comment by danielrbrowne** [comment]
@jonheslop I _think_ this would be the correct link: https://pusher.com/docs/channels/server_api/webhooks/  - does this seem right?

**Comment by jonheslop** [comment]
Oops yeah that’s a really old link, the old docs had a 301 redirect setup for this. I’ve updated the link within the Dashboard so this is now fixed.
