### ISSUE TITLE
Authenticating userspage

### ISSUE THREAD

**Issue by rinslow** [pusher/docs#40]
Hello there, I have a question regarding the Authentication server API.
Imagine a user has an access to a pusher channel, which is later revoked from him.

Is there a way for the server to send a `Deauth` message that will disconnect the client's websocket with Pusher's servers?

**Comment by ben-pusher** [comment]
We don't currently have any native way to force a disconnection from the server side. It is possible to build such logic into your solution, however this relies on a well behaved client and so could not guarantee that a malicious actor would be removed. 

This is an enquiry best suited for our support team, available via https://support.pusher.com/hc/en-us. We would prefer to keep the issues section for issues specifically related to our documentation. If you have any follow up queries please get in touch with support.
