### ISSUE TITLE
Publish payloadspage

### ISSUE THREAD

**Issue by fromi** [pusher/docs#43]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/publish-payloads/

The documentation provides this example: `hide_notification_if_site_has_focus: true`
However, the Typescript typing of the project expects a **string**, not a **boolean**.
I use the latest version: `"@pusher/push-notifications-server": "^1.2.3"`

**Comment by fromi** [comment]
After running some tests, it is a typescript typing issue and I had to do that do get the feature working:
`hide_notification_if_site_has_focus: (true as unknown as string)`

**Comment by ben-pusher** [comment]
Hey, this sounds like an issue with the push notifications library rather than our docs - could you raise an issue there?
