### ISSUE TITLE
Publish APIpage

### ISSUE THREAD

**Issue by hartmut-co-uk** [pusher/docs#50]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/publish-api/

The request body 'key' for [Publishing a notification to user(s)](https://pusher.com/docs/beams/reference/publish-api/#request-body-1) for FCM surely shouldn't be named 'apns' but also 'fcm', same as for the interests endpoint?

**Comment by hartmut-co-uk** [comment]
https://github.com/pusher/docs/pull/51

**Comment by ccaseypusher** [comment]
Hi, Thanks so much for your issue submission and pull request. This has now been merged so I will close the issue.
