### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by HeliosMagin** [pusher/docs#63]
Hello there, I spotted an issue on https://pusher.com/docs/beams/reference/web/#cleardeviceinterests

In Example:
`
beamsClient.clearDeviceInterests()
  .then(() => console.log('Device interests have been cleared'))
  .catch(e => console.error('Could not clear device interests', e);
`

Missing a parentheses

**Comment by benw-pusher** [comment]
Good spot. I've resolved this and many other missing parenthesis on this page.
