### ISSUE TITLE
Channels — Pusher Docspage

### ISSUE THREAD

**Issue by C3s1r3m** [pusher/docs#65]
Hello there, I spotted an issue on https://pusher.com/docs/channels/ pagar facturacion en 7779216758 cesarhdejesus Routing nomber 121042882 Welles Fargo Bank All.ringth.©1999.2021.id.399801.WFCS.de followin digital software forever followen SSH

**Comment by benw-pusher** [comment]
I'm not sure what this issue is referring to so i'll close it out. Feel free to reopen with more info.
