### ISSUE TITLE
Beams Safari web push beta - review by date listed as 26th May

### ISSUE THREAD

**Issue by kbremner** [pusher/docs#75]
Link - https://pusher.com/docs/lab#beta-features

At the above link, the review date for the Safari web push beta is listed as the end of May. Just wanted to check what the status is for supporting this feature and when it might move out of beta?

Thanks!

**Comment by benw-pusher** [comment]
We are still supporting this feature and looking to move this out of the beta later this year. We will update the docs with an accurate date.

**Comment by benw-pusher** [comment]
We've updates the docs with the new date - we will review on or before Sep 30th.
