### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by IceBotYT** [pusher/docs#91]
Hello there, I spotted an issue on https://pusher.com/docs/beams/guides/publish-to-specific-user/web/

Deprecated express usage in the Node.js tab of the code example here: https://pusher.com/docs/beams/guides/publish-to-specific-user/web/#creating-a-beams-auth-endpoint

Use `res.status(status).send(body)` instead of `res.send(status, body)`

**Comment by benw-pusher** [comment]
proposed change looks correct, will update. https://expressjs.com/en/api.html#res.send
